apiVersion: v1
kind: Service
metadata:
  name: bd-api
spec:
  type: ClusterIP
  selector:
    app: bd-api-persona
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306 # puertos que usan los pods